# Generated by Django 2.0 on 2019-11-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0002_auto_20191116_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='')),
                ('season', models.CharField(blank=True, default='', max_length=20)),
                ('episode', models.CharField(blank=True, default='', max_length=20)),
                ('publication_time', models.DateTimeField(blank=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('quality', models.CharField(blank=True, default='', max_length=20)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torrents', to='shows.Show')),
            ],
        ),
    ]
