# Generated by Django 2.0 on 2019-11-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='feed_name',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
