# Generated by Django 2.2.7 on 2019-12-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_torrent_feed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='title',
            field=models.CharField(default='', max_length=2160),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='publication_time',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
