# Generated by Django 2.2.8 on 2019-12-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0004_auto_20191210_0627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrent',
            options={'ordering': ('-season', '-episode')},
        ),
    ]
