# Generated by Django 3.0 on 2019-12-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20191221_1305'),
        ('torrents', '0006_auto_20191220_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='torrents', to='feeds.Feed'),
        ),
    ]
