# Generated by Django 3.0 on 2019-12-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0008_auto_20191221_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
