# Generated by Django 3.0 on 2019-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0009_auto_20191221_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
