# Generated by Django 3.0 on 2019-12-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0010_auto_20191221_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrent',
            options={'ordering': ('show', '-season', '-episode', 'feed')},
        ),
    ]
