# Generated by Django 3.0.4 on 2020-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0012_torrent_transmission_torrent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='download_status',
            field=models.CharField(choices=[('N', 'Never Started'), ('D', 'Downloading'), ('R', 'Ready')], default='N', max_length=1),
        ),
    ]
