# Generated by Django 3.0.4 on 2020-04-18 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0013_torrent_download_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='torrent',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
