# Generated by Django 3.0.4 on 2020-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0014_auto_20200418_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='profile_match_score',
            field=models.IntegerField(default=0),
        ),
    ]
