# Generated by Django 3.0.4 on 2020-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0015_torrent_profile_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='profile_match',
            field=models.BooleanField(default=False),
        ),
    ]
