# Generated by Django 3.0.4 on 2020-04-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0016_torrent_profile_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrent',
            options={'ordering': ('show', '-season', '-episode', '-profile_match_score', 'feed')},
        ),
    ]
