# Generated by Django 3.0.4 on 2020-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0017_auto_20200425_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='percent_done',
            field=models.IntegerField(default=0),
        ),
    ]
