# Generated by Django 3.0.4 on 2020-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0018_torrent_percent_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='download_status',
            field=models.CharField(choices=[('N', 'Never Started'), ('D', 'Downloading'), ('R', 'Ready'), ('S', 'Stopped')], default='N', max_length=1),
        ),
    ]
