# Generated by Django 3.2 on 2022-05-08 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_feed_api_feed'),
        ('movies', '0002_auto_20220508_1640'),
        ('torrents', '0020_auto_20201225_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTorrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(default='', max_length=2160)),
                ('publication_time', models.CharField(blank=True, max_length=64)),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('quality', models.CharField(blank=True, default='', max_length=20)),
                ('transmission_torrent_id', models.IntegerField(blank=True, default=0)),
                ('download_status', models.CharField(choices=[('N', 'Never Started'), ('D', 'Downloading'), ('R', 'Ready'), ('S', 'Stopped')], default='N', max_length=1)),
                ('percent_done', models.IntegerField(default=0)),
                ('profile_match_score', models.IntegerField(default=0)),
                ('profile_match', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movie_torrents', to='feeds.feed')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrents', to='movies.movie')),
            ],
            options={
                'ordering': ('-profile_match_score', 'feed'),
            },
        ),
    ]
