# Generated by Django 3.2 on 2022-05-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_feed_api_feed'),
        ('torrents', '0021_movietorrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torrents', to='feeds.feed'),
        ),
    ]
