# Generated by Django 2.0 on 2019-11-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
