# Generated by Django 2.0 on 2019-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_time_format',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
