# Generated by Django 2.0 on 2019-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feed_feed_time_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=20),
        ),
    ]
