# Generated by Django 3.0 on 2019-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feed_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('-priority',)},
        ),
        migrations.AddField(
            model_name='feed',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
