# Generated by Django 3.0.4 on 2020-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20191221_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='has_subtitles',
            field=models.BooleanField(default=False),
        ),
    ]
