# Generated by Django 3.0.4 on 2020-09-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_feed_has_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='api_feed',
            field=models.BooleanField(default=False),
        ),
    ]
