# Generated by Django 2.0 on 2019-11-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24)),
                ('title', models.CharField(max_length=256)),
                ('air_time', models.DateTimeField(blank=True, null=True)),
                ('found', models.BooleanField(default=False)),
                ('torrent_link', models.URLField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24)),
                ('current_season', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=24)),
                ('title', models.CharField(default='', max_length=256)),
                ('status', models.CharField(choices=[('r', 'Running'), ('e', 'Ended'), ('u', 'Unknown'), ('w', 'Waiting')], default='u', max_length=24)),
                ('poster_link', models.URLField(default='')),
                ('slug', models.SlugField(default='', editable=False, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='show', to='shows.Show'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season', to='shows.Season'),
        ),
    ]
