# Generated by Django 2.0 on 2019-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='poster_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
