# Generated by Django 2.0 on 2019-11-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20191116_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.RemoveField(
            model_name='season',
            name='show',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
