# Generated by Django 2.2.8 on 2019-12-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20191130_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='year',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
