# Generated by Django 2.2.8 on 2019-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_number_of_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='runtime',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
