# Generated by Django 3.0 on 2019-12-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_show_runtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('title',)},
        ),
    ]
