# Generated by Django 3.0.4 on 2020-04-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_auto_20200425_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.ShowProfile'),
        ),
    ]
