# Generated by Django 3.0.4 on 2020-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20200425_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showprofile',
            name='wait',
            field=models.CharField(choices=[('N', "Don't Wait"), ('1D', '1 Day'), ('2D', '2 Days'), ('3D', '3 Days'), ('4D', '4 Days'), ('5D', '5 Days'), ('6D', '6 Days'), ('1W', '1 Week'), ('F', 'Forever')], default='1W', max_length=4),
        ),
    ]
