# Generated by Django 3.0.4 on 2020-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_auto_20200425_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showprofile',
            name='high_quality_source',
            field=models.BooleanField(default=True, help_text='Wait for high quality torrents sources'),
        ),
        migrations.AlterField(
            model_name='showprofile',
            name='quality',
            field=models.CharField(choices=[('720P', '720P'), ('1080P', '1080P'), ('4K', '4K')], default='1080P', help_text='Show video quality', max_length=10),
        ),
        migrations.AlterField(
            model_name='showprofile',
            name='subtitles',
            field=models.BooleanField(default=True, help_text='Are subtitles required'),
        ),
        migrations.AlterField(
            model_name='showprofile',
            name='wait',
            field=models.CharField(choices=[('N', "Don't Wait"), ('1D', '1 Day'), ('2D', '2 Days'), ('3D', '3 Days'), ('4D', '4 Days'), ('5D', '5 Days'), ('6D', '6 Days'), ('1W', '1 Week'), ('F', 'Forever')], default='1W', help_text='How long to wait before downloading best available match, if full match not found', max_length=4),
        ),
    ]
