# Generated by Django 3.0.4 on 2020-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_auto_20200425_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='showprofile',
            name='download_automatically',
            field=models.BooleanField(default=False),
        ),
    ]
