# Generated by Django 3.0.4 on 2020-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_auto_20200502_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
