# Generated by Django 3.0.4 on 2020-06-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_auto_20200612_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='type',
            field=models.CharField(choices=[('Show', 'Show'), ('Movie', 'Movie')], default='Show', max_length=16),
        ),
    ]
