# Generated by Django 3.0.4 on 2020-06-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_auto_20200612_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='lookup_names',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
