# Generated by Django 3.0.4 on 2020-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_add_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
