# Generated by Django 3.0.4 on 2020-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0020_show_next_episode_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='next_episode_time',
            field=models.CharField(default='', editable=False, max_length=256),
        ),
    ]
