# Generated by Django 3.0.4 on 2020-11-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0022_auto_20200724_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='palette',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
