# Generated by Django 3.0.4 on 2020-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0023_show_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='status_line',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
