# Generated by Django 3.0.4 on 2020-12-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0025_show_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(default='', max_length=256)),
                ('should_download', models.BooleanField(default=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='shows.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(default='', max_length=256)),
                ('should_download', models.BooleanField(default=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_episodes', to='shows.Season')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_episodes', to='shows.Show')),
            ],
        ),
    ]
