# Generated by Django 3.0.4 on 2020-12-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0027_auto_20201220_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('number',)},
        ),
    ]
