# Generated by Django 3.0.4 on 2021-01-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0028_auto_20201220_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('show', '-season', '-number')},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('show', '-number')},
        ),
    ]
