# Generated by Django 3.0.4 on 2021-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0029_auto_20210109_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='next_episode_season_status',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
