# Generated by Django 3.2 on 2021-12-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0030_show_next_episode_season_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='custom_lookup_names',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
