# Generated by Django 3.2 on 2021-12-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0031_show_custom_lookup_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='is_downloaded',
        ),
        migrations.RemoveField(
            model_name='season',
            name='downloaded',
        ),
    ]
