# Generated by Django 3.2 on 2022-05-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitles', models.BooleanField(default=True, help_text='Are subtitles required')),
                ('high_quality_source', models.BooleanField(default=True, help_text='Wait for high quality torrents sources')),
                ('download_automatically', models.BooleanField(default=False)),
                ('wait', models.CharField(choices=[('N', "Don't Wait"), ('1D', 'Up to a Day'), ('2D', 'Up to 2 Days'), ('3D', 'Up to 3 Days'), ('4D', 'Up to 4 Days'), ('5D', 'Up to 5 Days'), ('6D', 'Up to 6 Days'), ('1W', 'Up to a Week'), ('F', 'Forever')], default='1W', help_text='How long to wait before downloading best available match, if full match not found', max_length=4)),
                ('quality', models.CharField(choices=[('720P', '720P'), ('1080P', '1080P'), ('4K', '4K')], default='1080P', help_text='Movie video quality', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieprofile'),
        ),
    ]
