# Generated by Django 3.2 on 2022-05-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_year_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(blank=True, default='9999-99-99', max_length=24),
        ),
    ]
